version: '3'

services:
  nginx-backend:
    ports:
      - "8082:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  
  backend:
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - SECRET_KEY=${OPENAI_SECRET}
    