version: '3'

services:
  backend:
    env_file:
        - '.backend.env'
    volumes:
      - ./backend:/app/backend:ro

  frontend:
    env_file:
      - '.frontend.env'
    volumes:
      - ./frontend:/app/frontend:ro