version: '3'

services:
  frontend:
    image: piotrchrusciel/llmtrivia-frontend:latest
  nginx-backend:
    ports:
      - "8082:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  
  backend:
    image: piotrchrusciel/llmtrivia-backend:latest
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - SECRET_KEY=${OPENAI_SECRET}
    