version: '3'

services:
  nginx-backend:
    ports:
      - "443:8443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  
  backend:
    env_file: []
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - SECRET_KEY=${OPENAI_SECRET}
  
  frontend:
    env_file: []
      