version: '3'

services:
  frontend:
    image: piotrchrusciel/llmtrivia-frontend:latest
    build:
      args:
        - BACKEND_HOST=${BACKEND_HOST}
        - APP_GOOGLE_CLIENT_ID=${APP_GOOGLE_CLIENT_ID}
  nginx-backend:
    ports:
      - "8082:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  
  backend:
    image: piotrchrusciel/llmtrivia-backend:latest
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - OPENAI_SECRET=${OPENAI_SECRET}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - SECRET_KEY=${SECRET_KEY}
