version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - '.backend.env'
    environment:
      - BACKEND_PORT=5000
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        - API_HOST=backend
        - API_PORT=5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    env_file:
      - '.frontend.env'
    environment:
      - BACKEND_PORT=5000
      - BACKEND_HOST=127.0.0.1
      - FRONTEND_PORT=3000
    depends_on:
      - backend
