version: '3'

services:
  backend:
    env_file:
        - './backend/.backend.env'
    volumes:
      - ./backend:/app/backend
      - ./docker/entrypoint.dev.sh:/app/entrypoint.dev.sh
    entrypoint: /app/entrypoint.dev.sh

    ports:
     - "5678:5678" # Debug port

  frontend:
    env_file:
      - './frontend/.frontend.env'
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro