version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    image: piotrchrusciel/llmtrivia-backend:latest
    env_file:
      - ./backend/.backend.env
    networks:
      - llm_network
    volumes:
      - ./backend:/app/backend

  nginx-backend:
    image: nginx:latest
    ports:
      - "8002:8002"
    volumes:
      - ./resources/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - llm_network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    image: piotrchrusciel/llmtrivia-frontend:latest
    depends_on:
      - backend
    networks:
      - llm_network
    ports:
      - "8001:8001"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
    
networks:
  llm_network:
    driver: bridge