name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker tag piotrchrusciel/llmtrivia-frontend:latest
        docker tag piotrchrusciel/llmtrivia-backend:latest
        docker push piotrchrusciel/llmtrivia-frontend:latest
        docker push piotrchrusciel/llmtrivia-backend:latest

    - name: Deploy to Live Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/llmtrivia.com
          docker-compose pull
          docker-compose up -d