name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        OPENAI_SECRET: ${{ secrets.OPENAI_SECRET }}
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
        docker tag piotrchrusciel/llmtrivia-frontend:latest piotrchrusciel/llmtrivia-frontend:latest
        docker tag piotrchrusciel/llmtrivia-backend:latest piotrchrusciel/llmtrivia-backend:latest
        docker push piotrchrusciel/llmtrivia-frontend:latest
        docker push piotrchrusciel/llmtrivia-backend:latest

    - name: Deploy to Live Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/llmtrivia.com
          docker-compose pull
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
